### ISSUE TITLE
[Proposal] Code of conduct addition

### ISSUE THREAD

**Issue by geromegrignon** [SubstraFoundation/welcome#2]
To clarify what you expect from contributor's behavior, it's a good practice to add a code of conduct.
A good solution is to use the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct).
If it sounds good to you, i can add it in each of the SubstraFoundation projects as a markdown file with a link into the Readme.md.

**Comment by inelgnu** [comment]
Hello @geromegrignon,

The organization already have a code of conduct which is global to all repositories defined here 
https://github.com/SubstraFoundation/.github/blob/master/CODE_OF_CONDUCT.md

Thank's

**Comment by geromegrignon** [comment]
Please consider adding a link to this code of conduct in each of the projects's Readme file.
From a contributor's point of view, a project is a single repository, not the whole organization. Contributors aren't used to check the organization to expect to know how the project works, the project should provide all the required information or at least links.

As an example, the kubernetes's repositories include a link to the [community repository](https://github.com/kubernetes/community).

**Comment by camillemarini** [comment]
Thanks a lot @geromegrignon . We'll do this! We haven't had the time to do it yet :-)
